"""StateStore Protocol. См. system_design §3.6.

В T-007 добавлены `seen_delivery` и `mark_pr_failed` (отдельный путь от done).
"""
from __future__ import annotations

from typing import Optional, Protocol

from sunsec.contracts import LLMResponseSchema


class StateStore(Protocol):
    async def mark_pr_in_progress(self, key: str, ttl: int = 86400) -> bool: ...
    async def mark_pr_done(self, key: str) -> None: ...
    async def mark_pr_failed(self, key: str) -> None: ...
    async def seen_delivery(self, delivery_id: str) -> bool: ...
    async def get_cached_llm_response(self, cache_key: str) -> Optional[LLMResponseSchema]: ...
    async def set_cached_llm_response(self, cache_key: str, response: LLMResponseSchema) -> None: ...
    async def has_posted_finding(self, repo: str, pr_number: int, finding_hash: str) -> bool: ...
    async def register_posted_finding(self, repo: str, pr_number: int, finding_hash: str) -> None: ...
